CREATE TABLE BOARD_INFO(
BOARD_NUM INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
BOARD_PARENT_NUM INT DEFAULT 0,
BOARD_TITLE VARCHAR(200) NOT NULL,
BOARD_FILE_PATH VARCHAR(200) DEFAULT '',
BOARD_CONTENT TEXT NOT NULL,
CREDATE DATETIME DEFAULT NOW(),
CREUSR INT NOT NULL,
MODATE DATETIME DEFAULT NOW(),
MODUSR INT NOT NULL
);

-- 계층형 INSERT TEST DATA

INSERT BOARD_INFO( BOARD_PARENT_NUM, BOARD_TITLE, BOARD_FILE_PATH, BOARD_CONTENT,CREUSR, MODUSR)
VALUES(0,'TEST TITLE1',NULL,'TEST CONTENT1',1,1),
(0,'TEST TITLE2',NULL,'TEST CONTENT2',1,1),
(0,'TEST TITLE3',NULL,'TEST CONTENT3',1,1),
(1,'SUB TITLE1',NULL,'SUB CONTENT1',1,1),
(2,'SUB TITLE2',NULL,'SUB CONTENT2',1,1),
(4,'SUB SUB TITLE1',NULL,'SUB SUB CONTENT4',1,1),
(0,'TEST TITLE4',NULL,'TEST CONTENT4',1,1);

-- 계층형 SELECT
WITH RECURSIVE BI AS(
SELECT 
	BOARD_NUM,
	BOARD_PARENT_NUM,
	BOARD_TITLE,
	BOARD_FILE_PATH,
	BOARD_CONTENT ,
	CREDATE,
	CREUSR,
	MODATE,
	MODUSR,
	1 LEVEL, 
	CAST(LPAD(BI1.BOARD_NUM,12,'0') AS CHAR(100)) as SORT
FROM BOARD_INFO BI1
WHERE BOARD_PARENT_NUM = 0
UNION ALL
SELECT 
	BI2.BOARD_NUM,
	BI2.BOARD_PARENT_NUM,
	BI2.BOARD_TITLE,
	BI2.BOARD_FILE_PATH,
	BI2.BOARD_CONTENT ,
	BI2.CREDATE,
	BI2.CREUSR,
	BI2.MODATE,
	BI2.MODUSR,
	1+ LEVEL LEVEL, 
	CAST(CONCAT(BI.SORT, '-',LPAD(BI2.BOARD_NUM,12,'0') ) AS CHAR(100)) as SORT
FROM BOARD_INFO BI2
INNER JOIN BI ON BI.BOARD_NUM = BI2.BOARD_PARENT_NUM)
SELECT * FROM BI ORDER BY SORT;

-- UPDATE
UPDATE BOARD_INFO
SET BOARD_TITLE='수정'
WHERE BOARD_NUM=1;

--DELETE
DELETE FROM BOARD_INFO WHERE BOARD_NUM=1;