CREATE TABLE NOTICE_BOARD(
NOTICE_NUM INT AUTO_INCREMENT PRIMARY KEY,
NOTICE_TITLE VARCHAR(200) NOT NULL,
NOTICE_WRITER VARCHAR(100),
NOTICE_DATE DATETIME DEFAULT NOW(),
NOTICE_CNT INT DEFAULT 0,
NOTICE_CONTENT TEXT NOT NULL,
USER_NUM INT NOT NULL,
FOREIGN KEY(USER_NUM) REFERENCES USER_TBL(USER_NUM)
);

-- CREATE : INSERT
INSERT INTO NOTICE_BOARD(NOTICE_TITLE, NOTICE_WRITER, NOTICE_CONTENT )
VALUES('공지 제목','관리자','공지 내용');
-- READ : SELECT

-- NOTICE_LIST
SELECT
	NOTICE_NUM,
	NOTICE_TITLE,
	NOTICE_WRITER,
	NOTICE_DATE,
	NOTICE_CNT
FROM NOTICE_BOARD
ORDER BY NOTICE_NUM DESC;

-- NOTICE_CONTENT
SELECT
	NOTICE_NUM,
	NOTICE_TITLE,
	NOTICE_WRITER,
	NOTICE_DATE,
	NOTICE_CNT,
	NOTICE_CONTENT
FROM NOTICE_BOARD
WHERE NOTICE_NUM = 1;
	
-- UPDATE : UPDATE
UPDATE NOTICE_BOARD
SET
	NOTICE_TITLE='공지 제목 수정',
	NOTICE_CONTENT='공지 내용 수정'
WHERE NOTICE_NUM = 1;

-- DELETE : DELETE
DELETE FROM NOTICE_BOARD
WHERE NOTICE_NUM = 1;