DROP TABLE QAN_BOARD;

CREATE TABLE QAN_BOARD(
QAN_NUM INT AUTO_INCREMENT PRIMARY KEY,
QAN_DATE DATE DEFAULT NOW(),
QAN_STATUS VARCHAR(50) DEFAULT '미완료',
QAN_TITLE VARCHAR(200) NOT NULL,
QAN_CONTENT TEXT NOT NULL,
QAN_FILE VARCHAR(200) DEFAULT '',
QAN_ANSWER TEXT DEFAULT '미완료된 문의입니다.',
USER_NUM INT NOT NULL,
FOREIGN KEY(USER_NUM) REFERENCES USER_INFO(USER_NUM)
);

-- Create
INSERT INTO QAN_BOARD(USER_NUM, QAN_TITLE, QAN_CONTENT, QAN_FILE)
VALUES(1, '첫번째 문의', '첫번째 문의입니다.', '');

-- Read
-- 내 문의 목록
SELECT QAN_NUM, QAN_DATE, QAN_TITLE, QAN_STATUS
FROM QAN_BOARD
WHERE USER_NUM=1;
-- 내 문의 상세 정보
SELECT QAN_DATE, QAN_STATUS, QAN_TITLE, QAN_CONTENT, QAN_FILE, QAN_ANSWER
FROM QAN_BOARD
WHERE QAN_NUM=1;

-- Update
UPDATE QAN_BOARD
SET QAN_STATUS='완료', QAN_ANSWER='답변입니다.'
WHERE QAN_NUM=1;

-- Delete