CREATE TABLE REVIEW_BOARD_INFO(
BOARD_NUM INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
BOARD_RATED VARCHAR(100) DEFAULT '☆☆☆☆☆',
BOARD_JENRE VARCHAR(100),
BOARD_TITLE VARCHAR(200) NOT NULL,
BOARD_CONTENT TEXT NOT NULL,
BOARD_WRITER VARCHAR(100) NOT NULL,
BOARD_RCMD_NUM INT DEFAULT 0,
BOARD_DATE DATETIME DEFAULT NOW(),
BOARD_CNT INT DEFAULT 0
);

-- CREATE : INSERT
INSERT INTO REVIEW_BOARD_INFO( BOARD_RATED, BOARD_JENRE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER )
VALUES( '☆☆☆☆☆', '액션', '제목','내용','글쓴이' );
INSERT INTO REVIEW_BOARD_INFO( BOARD_RATED, BOARD_JENRE, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER )
VALUES( '★★★★★', '판타지', '신비한 동물들과 덤블도어의 비밀 ','내용','글쓴이' );

-- READ : SELECT

-- BOARD_LIST
SELECT
	BOARD_NUM,
	BOARD_RATED,
	BOARD_JENRE,
	BOARD_TITLE,
	BOARD_WRITER,
	BOARD_RCMD_NUM,
	BOARD_DATE,
	BOARD_CNT
FROM REVIEW_BOARD_INFO;

--BOARD_READ
SELECT
	BOARD_NUM,
	BOARD_RATED,
	BOARD_JENRE,
	BOARD_TITLE,
	BOARD_CONTENT,
	BOARD_WRITER,
	BOARD_RCMD_NUM,
	BOARD_DATE,
	BOARD_CNT
FROM REVIEW_BOARD_INFO
WHERE BOARD_NUM=1;

-- UPDATE : UPDATE
UPDATE REVIEW_BOARD_INFO
SET
	BOARD_RATED='★★★☆☆',
	BOARD_JENRE='장르수정',
	BOARD_TITLE='제목수정',
	BOARD_CONTENT='내용수정'
WHERE BOARD_NUM=1;

-- DELETE : DELETE
DELETE FROM REVIEW_BOARD_INFO
WHERE BOARD_NUM=1;

DESC REVIEW_BOARD_INFO;
DROP TABLE REVIEW_BOARD_INFO;
